package beans;
// Generated 21.12.2016 19:55:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 * Customer generated by hbm2java
 */

@ManagedBean
@SessionScoped
public class Customer  implements java.io.Serializable {


     private String login;
     private String lastname;
     private String firstname;
     private String partonymic;
     private String password;
     private Set finisheds = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String login, String lastname, String firstname) {
        this.login = login;
        this.lastname = lastname;
        this.firstname = firstname;
    }
    public Customer(String login, String lastname, String firstname, String partonymic, String password, Set finisheds) {
       this.login = login;
       this.lastname = lastname;
       this.firstname = firstname;
       this.partonymic = partonymic;
       this.password = password;
       this.finisheds = finisheds;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getPartonymic() {
        return this.partonymic;
    }
    
    public void setPartonymic(String partonymic) {
        this.partonymic = partonymic;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getFinisheds() {
        return this.finisheds;
    }
    
    public void setFinisheds(Set finisheds) {
        this.finisheds = finisheds;
    }

    public String login() {
        
            return "index";

    }

    public String logout() {
        String result = "/login.xhtml?faces-redirect=true";

        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

        try {
            request.logout();
        } catch (ServletException e) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, e);
        }

        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();

        return result;
    }


}


