package beans;
// Generated 21.12.2016 19:55:33 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Finished generated by hbm2java
 */
public class Finished  implements java.io.Serializable {


     private BigDecimal id;
     private Customer customer;
     private String adress;
     private Serializable send;

    public Finished() {
    }

    public Finished(BigDecimal id, Customer customer, String adress, Serializable send) {
       this.id = id;
       this.customer = customer;
       this.adress = adress;
       this.send = send;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public Serializable getSend() {
        return this.send;
    }
    
    public void setSend(Serializable send) {
        this.send = send;
    }




}


