package beans;
// Generated 21.12.2016 19:55:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GenreBookId generated by hbm2java
 */
public class GenreBookId  implements java.io.Serializable {


     private BigDecimal idGenre;
     private BigDecimal idBook;

    public GenreBookId() {
    }

    public GenreBookId(BigDecimal idGenre, BigDecimal idBook) {
       this.idGenre = idGenre;
       this.idBook = idBook;
    }
   
    public BigDecimal getIdGenre() {
        return this.idGenre;
    }
    
    public void setIdGenre(BigDecimal idGenre) {
        this.idGenre = idGenre;
    }
    public BigDecimal getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(BigDecimal idBook) {
        this.idBook = idBook;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenreBookId) ) return false;
		 GenreBookId castOther = ( GenreBookId ) other; 
         
		 return ( (this.getIdGenre()==castOther.getIdGenre()) || ( this.getIdGenre()!=null && castOther.getIdGenre()!=null && this.getIdGenre().equals(castOther.getIdGenre()) ) )
 && ( (this.getIdBook()==castOther.getIdBook()) || ( this.getIdBook()!=null && castOther.getIdBook()!=null && this.getIdBook().equals(castOther.getIdBook()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdGenre() == null ? 0 : this.getIdGenre().hashCode() );
         result = 37 * result + ( getIdBook() == null ? 0 : this.getIdBook().hashCode() );
         return result;
   }   


}


