package beans;
// Generated 21.12.2016 19:55:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Publlisher generated by hbm2java
 */
public class Publlisher  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set books = new HashSet(0);

    public Publlisher() {
    }

	
    public Publlisher(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Publlisher(BigDecimal id, String name, Set books) {
       this.id = id;
       this.name = name;
       this.books = books;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


