--------------------------------------------------------
--  File created - воскресенье-декабря-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AUTHOR" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOK" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"ID_AUTHOR" NUMBER(*,0), 
	"YEAR" NUMBER(*,0), 
	"ID_PUBLISHER" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"PARTONYMIC" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINISHED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FINISHED" 
   (	"ID" NUMBER(*,0), 
	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(200 BYTE), 
	"SEND" BINARY_DOUBLE DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GENRE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GENRE" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GENRE_BOOK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GENRE_BOOK" 
   (	"ID_GENRE" NUMBER(*,0), 
	"ID_BOOK" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GROUPS" 
   (	"ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_GROUPS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USER_GROUPS" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"GROUPID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AUTHOR
SET DEFINE OFF;
Insert into SYSTEM.AUTHOR (ID,NAME) values ('7','Джоан Роулинг');
Insert into SYSTEM.AUTHOR (ID,NAME) values ('8','Эльчин Сафарли');
REM INSERTING into SYSTEM.BOOK
SET DEFINE OFF;
Insert into SYSTEM.BOOK (ID,NAME,ID_AUTHOR,YEAR,ID_PUBLISHER) values ('1','Гарри Поттер и философский камень','7','2000','1');
REM INSERTING into SYSTEM.CUSTOMER
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER (LOGIN,LASTNAME,FIRSTNAME,PARTONYMIC,PASSWORD) values ('alex','Пархоменко','Александра',null,'password');
REM INSERTING into SYSTEM.FINISHED
SET DEFINE OFF;
REM INSERTING into SYSTEM.GENRE
SET DEFINE OFF;
REM INSERTING into SYSTEM.GENRE_BOOK
SET DEFINE OFF;
REM INSERTING into SYSTEM.GROUPS
SET DEFINE OFF;
REM INSERTING into SYSTEM.USER_GROUPS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AUTHOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AUTHOR_PK" ON "SYSTEM"."AUTHOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BOOKS_PK" ON "SYSTEM"."BOOK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CUSTOMER_PK" ON "SYSTEM"."CUSTOMER" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ALL_ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ALL_ORDERS_PK" ON "SYSTEM"."FINISHED" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GENRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GENRE_PK" ON "SYSTEM"."GENRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GROUPS_PK" ON "SYSTEM"."GROUPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger INSERT_AUTHOR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."INSERT_AUTHOR" 
   before insert on "SYSTEM"."AUTHOR" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select AUTHOR_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."INSERT_AUTHOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_BOOK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."INSERT_BOOK" 
   before insert on "SYSTEM"."BOOK" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select BOOK_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."INSERT_BOOK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_ORDER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."INSERT_ORDER" 
   before insert on "SYSTEM"."FINISHED" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ORD_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."INSERT_ORDER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_GENRE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."INSERT_GENRE" 
   before insert on "SYSTEM"."GENRE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select GENRE_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."INSERT_GENRE" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."AUTHOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AUTHOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOK" ADD CONSTRAINT "BOOKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BOOK" MODIFY ("ID_PUBLISHER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOK" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOK" MODIFY ("ID_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOOK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMER" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUSTOMER" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINISHED
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FINISHED" ADD CONSTRAINT "ALL_ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FINISHED" MODIFY ("SEND" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FINISHED" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FINISHED" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FINISHED" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GENRE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GENRE" ADD CONSTRAINT "GENRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GENRE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GENRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GENRE_BOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GENRE_BOOK" MODIFY ("ID_BOOK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GENRE_BOOK" MODIFY ("ID_GENRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GROUPS" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GROUPS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_GROUPS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_GROUPS" MODIFY ("GROUPID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_GROUPS" MODIFY ("USERID" NOT NULL ENABLE);
